; [windows]
; 10.10.1.4 \
; ansible_user=Admin \
; ansible_password="YourPassword" \
; ansible_connection=winrm \
; ansible_winrm_server_cert_validation=ignore \
; ansible_host_resource_id="/subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.Compute/virtualMachines/vm1"


; [linux]
; 10.20.3.7 \
; ansible_user=azureuser \
; ansible_ssh_private_key_file=~/.ssh/id_rsa \
; ansible_host_resource_id="/subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.Compute/virtualMachines/vm2"
