---
- name: Validate AMA status (Linux)
command: systemctl status azuremonitoragent
register: status_linux
ignore_errors: yes
when: ansible_os_family != 'Windows'


- name: Validate AMA status (Windows)
win_service:
name: AzureMonitorWindowsAgent
state: started
when: ansible_os_family == 'Windows'


- debug:
msg: "Linux AMA status: {{ status_linux.stdout | default('Not applicable') }}"
when: ansible_os_family != 'Windows'